### PR TITLE
fix:(#73)

### PR DESCRIPTION
**Pull request by zhangHongEn**

### CODE REVIEW

**Comment by zhangHongEn** [comment]
The single test needs to be supplemented, so it has not been merged yet.
If anyone encounters this problem in the project, you can leave a message here to tell us that it needs to be released

**Comment by HuntFeng** [comment]
Hi, thanks for the hard work! I encounter the issue #73 as well when trying to unmount a react component. May I know when will this pr be merged?

**Comment by zhangHongEn** [comment]
@devilwjp Unit test case completion

**Comment by devilwjp** [comment]
@HuntFeng 2.3.15

**Comment by HuntFeng** [comment]
Thank you guys for your hard work! Appreciate it!

**Pull request closed without merging**
